description: "Serious Fucking Index"
name: "disktree"
keywords: ["disktree"]
theme: "default"
repository: "https://github.com/disktree/ii"

contact:
  organization: "disktree"
  email: admin@disktree.net
  web: https://disktree.net

git:
  branch: main

github:
  user: "disktree"
  repo: "ii"

social:
  bandcamp: "disktree"
  github: "tong"
  mixcloud: "disktree"
  soundcloud: "disktree"
  twitter: "disktree"
  vimeo: "disktree"
